#!/bin/sh

TMPDIR="tmp.$$"

if ! mkdir $TMPDIR; then
    echo mkdir $TMPDIR failed
    exit 1
fi

expect="autobuild,project=autobuild,revision=1.0,mode=default,hosttype=i686-pc-linux-gnu,buildtype=i686-pc-linux-gnu,hostname=latte,timestamp=20040706-232434,status=ok,log.txt"
filename=`./autobuild -o $TMPDIR logs/autobuild.log`
err=$?

if test "$err" != "0"; then
    echo Running autobuild failed: $err
    rmdir $TMPDIR
    exit 1
fi

if test "$filename" != "$TMPDIR/$expect"; then
    echo File name mismatch
    echo Expected: $expect
    echo Got: $filename
    rm -f $filename
    rmdir $TMPDIR
    exit 1
fi

if ! cmp $filename logs/autobuild.log; then
    echo File comparison failed
    rm -f $filename
    rmdir $TMPDIR
    exit 1
fi

rm -f $filename
rmdir $TMPDIR
exit 0
