\input texinfo   @c -*-texinfo-*-
@comment $Id: autobuild.texi,v 1.2 2004-07-08 14:02:44 jas Exp $
@comment %**start of header
@setfilename autobuild.info
@include version.texi
@settitle Autobuild @value{VERSION}
@syncodeindex pg cp
@comment %**end of header
@copying
This manual is last updated @value{UPDATED} for version
@value{VERSION} of GNU Libidn.

Copyright @copyright{} 2004 Simon Josefsson.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end quotation
@end copying

@dircategory Development
@direntry
* autobuild: (autobuild).	Generate HTML information from software builds.
@end direntry

@dircategory GNU utilities
@direntry
* autobuild: (autobuild)Invoking autobuild.	Process build logs.
* abindex: (autobuild)Invoking abindex.		Create indexes for build logs.
@end direntry

@titlepage
@title Autobuild
@subtitle for version @value{VERSION}, @value{UPDATED}
@author Simon Josefsson (@email{bug-autobuild@@josefsson.org})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Autobuild

@insertcopying
@end ifnottex

@menu
* Introduction::
* Integrating autobuild.m4 in your project::
* Invoking autobuild::
* Invoking abindex::
* Copying This Manual::
* Index::
@end menu

@node Introduction
@chapter Introduction

Autobuild is a package that process output from building software,
primarily focused on packages using Autoconf and Automake, and then
generate a HTML summary file, containing links to each build log.  The
output include project name, version, build host types (cross compile
aware), compiler host name, date of build, and indication of success
or failure.  The output is indexed in many ways to simplify browsing.

The quickest way to get an understanding of what Autobuild can do for
you, is to look at some example output.  For now, we recommend looking
at how Autobuild is used in the GNU Libidn project, see
@url{http://josefsson.org/autobuild-logs/libidn.html}.

@node Integrating autobuild.m4 in your project
@chapter Integrating autobuild.m4 in your project


@node Invoking autobuild
@chapter Invoking autobuild

@pindex autobuild
@cindex invoking @command{autobuild}

This is a autobuild manual.  There is no autobuild program to
invoke, but if there was, you could see its basic usage
and command line options here.

@node Invoking abindex
@chapter Invoking abindex

@pindex abindex
@cindex invoking @command{abindex}

This is a autobuild manual.  There is no autobuild program to invoke,
but if there was, you could see its basic usage and command line
options here.


@node Copying This Manual
@appendix Copying This Manual

@menu
* GNU Free Documentation License::  License for copying this manual.
@end menu

@include fdl.texi


@node Index
@unnumbered Index

@printindex cp

@bye
